[package]
name = "pgpaste-server"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.17", features = ["json"] }
diesel = { version = "2.0.4", features = ["postgres"] }
diesel-async = { version = "0.2.2", features = ["postgres", "deadpool"] }
diesel_migrations = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15.7"
eyre = "0.6.8"
names = "0.14.0"
pgpaste-api-types = { path = "../pgpaste-api-types" }
secrecy = "0.8.0"
sequoia-net = "0.27.0"
sequoia-openpgp = "1.14.0"
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["tracing", "trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
