[package]
name = "pgpaste-cli"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.2.5", features = ["derive"] }
eyre = "0.6.8"
reqwest = { version = "0.11.17", features = ["multipart", "blocking"] }
sequoia-net = "0.27.0"
sequoia-openpgp = "1.14.0"
serde_json = "1.0.96"
