[package]
name = "pgpaste-cli"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.2.5", features = ["derive"] }
dirs = "5.0.1"
eyre = "0.6.8"
pgpaste-api-types = { path = "../pgpaste-api-types" }
reqwest = { version = "0.11.17", features = ["blocking"] }
sequoia-openpgp = "1.14.0"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
toml = "0.7.3"
