[package]
name = "pgpaste-cli"
description = "A command line interface for pgpaste"
repository = "https://github.com/MrNossiom/pgpaste"
categories = ["command-line-utilities"]
keywords = ["pgpaste", "clipboard", "api", "cli", "paste"]
readme = "../README.md"
version = "0.0.0"
edition = "2021"
license = "CECILL-B"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pgpaste"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.71"
async-compat = "0.2.1"
atty = "0.2.14"
clap = { version = "4.2.5", features = ["derive"] }
clap_complete = "4.2.3"
dirs = "5.0.1"
duration-human = "0.1.10"
eyre = "0.6.8"
pgpaste-api-types = { workspace = true }
reqwest = { version = "0.11.17", features = ["blocking"] }
rmp-serde = "1.1.1"
rpassword = "7.2.0"
sequoia-net = "0.27.0"
sequoia-openpgp = "1.14.0"
serde = { version = "1.0.162", features = ["derive"] }
smol = "1.3.0"
toml = "0.7.3"
