[package]
name = "pgpaste-api-types"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
time = { version = "0.3.21", features = ["serde"] }

[dev-dependencies]
rmp-serde = "1.1.1"
